#include "tokenizer.h"

#include <stdbool.h>
#include <string.h>

#include "vendor/iree/runtime/src/iree/base/api.h"
#include "vendor/iree/runtime/src/iree/tokenizer/format/huggingface/tokenizer_json.h"
#include "vendor/iree/runtime/src/iree/tokenizer/tokenizer.h"

/* Embedded HuggingFace tokenizer.json (Auto-generated by
 * scripts/generate_tokenizer_data.py at build time).  We hand the raw
 * bytes to IREE's parser at runtime, so llmoe itself needs no JSON
 * parser, no PCRE2, and no utf8proc. */
#include "tokenizer_data.inc"

/* Process-lifetime lazy init.  The IREE tokenizer is immutable and
 * thread-safe (per IREE's tokenizer.h), so a single shared instance is
 * fine for an inference engine that lives for the whole process.  We
 * never free it: tearing it down adds exit-ordering surface with no
 * benefit for a short-lived CLI. */
static iree_tokenizer_t* g_tokenizer;
static enum { TOK_UNINIT = 0, TOK_OK, TOK_FAILED } g_tok_state;

static bool ensure_tokenizer(void)
{
    if (g_tok_state == TOK_OK) return true;
    if (g_tok_state == TOK_FAILED) return false;

    iree_string_view_t json = iree_make_string_view(
        (const char*)kTokenizerJsonData, kTokenizerJsonDataLen);
    iree_status_t s = iree_tokenizer_from_huggingface_json(
        json, iree_allocator_system(), &g_tokenizer);
    if (!iree_status_is_ok(s) || g_tokenizer == NULL) {
        iree_status_ignore(s);
        g_tok_state = TOK_FAILED;
        return false;
    }
    g_tok_state = TOK_OK;
    return true;
}

/* Encode `text` into a freshly IREE-allocated scratch buffer sized to an
 * upper bound, then copy out into the caller's buffer if it fits.
 *
 * Upper bound: IREE's ByteLevel segmenter never emits more than one
 * token per input byte (each pre-token collapses to <=1 BPE-fused token
 * per byte of its byte-level encoding), so `len + 1` slots is always
 * sufficient (+1 just guards the pathological empty-pre-token case). */
static size_t encode_into_scratch(const char* text, size_t len,
                                  iree_tokenizer_token_id_t** out_scratch)
{
    iree_host_size_t cap = (iree_host_size_t)len + 1;
    iree_tokenizer_token_id_t* scratch = NULL;
    iree_status_t s = iree_allocator_malloc(
        iree_allocator_system(), cap * sizeof(*scratch), (void**)&scratch);
    if (!iree_status_is_ok(s)) {
        iree_status_ignore(s);
        return 0;
    }

    iree_host_size_t count = 0;
    s = iree_tokenizer_encode(
        g_tokenizer, iree_make_string_view(text, len),
        IREE_TOKENIZER_ENCODE_FLAG_NONE,
        iree_tokenizer_make_token_output(scratch, NULL, NULL, cap),
        iree_allocator_system(), &count);
    if (!iree_status_is_ok(s)) {
        iree_status_ignore(s);
        iree_allocator_free(iree_allocator_system(), scratch);
        return 0;
    }
    *out_scratch = scratch;
    return (size_t)count;
}

size_t olmoe_tokenize(const char* text, olmoe_token_id_t* out, size_t cap)
{
    if (!text) return 0;
    size_t len = strlen(text);
    if (len == 0) return 0;
    if (!ensure_tokenizer()) return 0;

    iree_tokenizer_token_id_t* scratch = NULL;
    size_t count = encode_into_scratch(text, len, &scratch);
    if (count == 0) {
        /* count==0 with non-empty input is a legitimate result (e.g. a
         * normalizer that drops everything); scratch may still be
         * allocated and must be freed. */
        if (scratch) iree_allocator_free(iree_allocator_system(), scratch);
        return 0;
    }

    if (out && cap >= count) {
        /* Both id types are 32-bit; OLMoE ids are non-negative so the
         * bit pattern copies cleanly between IREE's int32_t and our
         * uint32_t. */
        memcpy(out, scratch, count * sizeof(*out));
    }
    iree_allocator_free(iree_allocator_system(), scratch);
    return count;
}